GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDE4ODcwOTksImV4cCI6MTcwMTg4NzExOSwiYXVkIjoiNjU3MGEzOTkxMzg1MGFkZTNlOWI5ODRhIiwiaXNzIjoiRGF0YVZpelggVGVhbSJ9.98dJdcF6G1uCeQ-QmUhpQYjbhPiWCQK1Ec154m6cL14
###Login route

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "identifier": " ",
    "password" : "  "
}
###Register route

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "userName": "   ",
    "email": "  ",
    "password" : " "
}
###Refresh-token route

POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDE2MTk3MzYsImV4cCI6MTczMzE3NzMzNiwiYXVkIjoiNjU2YWRhNzkyNjkwMmQzOTk2MzM0ZDA4IiwiaXNzIjoiRGF0YVZpelggVGVhbSJ9.AfCsYQzGUXqyl4LmmYukYWI98Q-VuhxQlDVg9bpX_PU"

}
###Logout route

DELETE http://localhost:3000/auth/logout
Content-Type: : application/token
{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDE2MjIyMzksImV4cCI6MTczMzE3OTgzOSwiYXVkIjoiNjU2YWRhNzkyNjkwMmQzOTk2MzM0ZDA4IiwiaXNzIjoiRGF0YVZpelggVGVhbSJ9.casMHT2zH9r4EZUhnIPhZzHM1mJhdJQOAzJBg-ycphY"
}